# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift
permissions: write-all
  env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    GH_WS: ${{github.WORKSPACE}}
on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make
    - name: Create Release
      run: |
        gh release create 1.0 "${GW_WS}/.build/release/" -t "resolve-alias"
      
